### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by tom20180126** [tom20180126/chat-space#10]
# IPアドレス
54.199.74.45

**Comment by naru6117** [comment]
ご提出ありがとうございます！
確認させていただきましたが、修正箇所ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
※今後実装に関する質問がありましたら、メンターに確認をお願いします！

**Comment by tom20180126** [comment]
ありがとうございました。
